import {
  Activity,
  Banknote,
  Boxes,
  ChartColumn,
  ClipboardList,
  Cog,
  Droplets,
  Gift,
  History,
  House,
  MapPin,
  Package,
  Radio,
  Receipt,
  ShieldCheck,
  Truck,
  User,
  UserCheck,
  UserCog,
  Users,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "./nav-config";

/** Resolves the icon names used by the navigation map to components. */
export const NAV_ICONS: Record<IconName, LucideIcon> = {
  activity: Activity,
  banknote: Banknote,
  boxes: Boxes,
  chart: ChartColumn,
  clipboard: ClipboardList,
  cog: Cog,
  droplets: Droplets,
  gift: Gift,
  history: History,
  home: House,
  mapPin: MapPin,
  package: Package,
  radio: Radio,
  receipt: Receipt,
  shieldCheck: ShieldCheck,
  truck: Truck,
  user: User,
  userCheck: UserCheck,
  userCog: UserCog,
  users: Users,
};
